### ISSUE TITLE
Requisitos Funcionales

### ISSUE THREAD

**Issue by danieltm1987** [DanielRM120/ProyectoMascotasCiclo3#2]
- Cada cambio que hagas Johana por favor habla con Daniel Alfonso para que corrija o agregue el caso de uso.
- Cada avance que hagan tienen que documentarlo en comentarios (abajo de esta descripción) ejemplo : "hoy se hizo una corrección y se agregaron 2 requisitos más".
- Si tienen dudas, hablar con el Líder.

**Comment by DanielRM120** [comment]
Johana encargada de esta actividad

**Comment by JohanaGonza** [comment]
Se Realiza las Respectivas Correcciones  de los requisitos funcionales
