### ISSUE TITLE
Requisitos No Funcionales

### ISSUE THREAD

**Issue by danieltm1987** [DanielRM120/ProyectoMascotasCiclo3#3]
- Cada avance que hagan tienen que documentarlo en comentarios (abajo de esta descripción) ejemplo : "hoy se hizo una corrección y se agregaron 2 requisitos más".
- Si tiene dudas, hablar con el Líder.

**Comment by DanielRM120** [comment]
Stiven encargado de la actividad

**Comment by stiven23R** [comment]
Se realizaron 10 requisitos no funcionales,

**Comment by stiven23R** [comment]
se agrego un requisito mas al proyecto
