### ISSUE TITLE
Introducción y Objetivos (General y específicos)

### ISSUE THREAD

**Issue by DanielRM120** [DanielRM120/ProyectoMascotasCiclo3#6]
- Cada cambio que haga Martin, si es necesario, por favor hablar con Johana y Stiven para que corrija o agregue los requisitos (opcional).
- Cada avance que hagan tienen que documentarlo en comentarios (abajo de esta descripción) ejemplo : "hoy se hizo una corrección y se agregaron 2 requisitos más".
- Si tiene dudas, hablar con el Líder.

**Comment by DanielRM120** [comment]
Martin encargado de esta actividad

**Comment by NtmNitram** [comment]
Introducción y Objetivo general redactados, A la espera de requisitos para redactar los objetivos especificos
