### ISSUE TITLE
Diagramas de Caso de uso

### ISSUE THREAD

**Issue by DanielRM120** [DanielRM120/ProyectoMascotasCiclo3#7]
- Cada avance que hagan tienen que documentarlo en comentarios (abajo de esta descripción) ejemplo : "hoy se hizo una corrección y se agregaron 2 requisitos más".
- Si tiene dudas, hablar con el Líder.

**Comment by danieltm1987** [comment]
Se  revisa y ajusta el caso de uso de Requisito #1 R1 Entrada del usuario al sistema

**Comment by danieltm1987** [comment]
Se revisa y ajusta el caso de uso de Requisito R2 Visualización de información mascotas

**Comment by danieltm1987** [comment]
Se revisa y ajusta el caso de uso de Requisito R3 Entradas de Registro de información en el sistema

**Comment by danieltm1987** [comment]
Se revisa y ajusta el caso de uso de Requisito R4 Módulos de registro de Mascotas por usuario

**Comment by danieltm1987** [comment]
Se revisa y ajusta el caso de uso de Requisito R5 Módulo de Visitas Domiciliaria

**Comment by danieltm1987** [comment]
Se revisa y ajusta el caso de uso de R6 Módulo de búsqueda
